Add the security guidelines to the readme
neo4j/docs-status-codes pull request #107
Opened 2023-12-21 15:13 UTC by renetapopova

2023-12-21 15:28 UTC, renetapopova commented
Do you think we'll benefit if we add these references to the guidelines:

* https://cheatsheetseries.owasp.org/cheatsheets/Logging_Vocabulary_Cheat_Sheet.html
* https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html

2023-12-21 16:11 UTC, Lojjs requested changes
Really good! Just one thing which I think can be adjusted to be clearer, see suggestion

2023-12-21 16:11 UTC, Lojjs commented on README.adoc
> +* For wrapped errors, it is safe to reuse error messages only if they are coming from Neo4j, i.e. have a status.
```suggestion
* Do not use error messages from underlying libraries/dependencies (e.g. Java runtime errors) but always catch the error and throw your own error message. It is safe to reuse error messages only if they are coming from Neo4j, i.e. have a Neo4j status code.
```

2023-12-21 16:13 UTC, Lojjs commented
> Do you think we'll benefit if we add these references to the guidelines:
> 
> * https://cheatsheetseries.owasp.org/cheatsheets/Logging_Vocabulary_Cheat_Sheet.html
> * https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html

Maybe if we add them in the bottom of the section, with a note that clarifies that it is further information for those interested and not a requirement to read?

2023-12-22 08:37 UTC, Lojjs approved these changes

2024-01-04 12:11 UTC, merged