Add GQLstatus to `DynamicProperty` and `CodeGenerationFailed`
neo4j/docs-status-codes pull request #149
Opened 2024-06-20 14:08 UTC by NataliaIvakina

2024-06-20 14:10 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-149.surge.sh

Updated pages:
- [List of all notification codes](https://neo4j-docs-status-codes-149.surge.sh/status-codes/5/notifications/all-notifications)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-24 08:30 UTC, Lojjs requested changes
A few modifications needed. I also realised something is a bit strange on our side with 01N40, wrote a Slack message about it. If we need to change something about it, that can be done separately from this PR

2024-06-24 08:30 UTC, Lojjs commented on modules/ROOT/pages/notifications/all-notifications.adoc
> +a|info: runtime unsupported.
```suggestion
a|warn: runtime unsupported.
```

2024-06-24 08:30 UTC, Lojjs commented on modules/ROOT/pages/notifications/all-notifications.adoc
> +The query cannot be executed `runtime=pipelined operatorEngine=compiled expressionEngine=compiled`, `runtime=pipelined operatorEngine=interpreted expressionEngine=compiled` is used. Cause: `method to
```suggestion
The query cannot be executed with `preparser_input1`, `preparser_input2` is used. Cause: `$msg`.
```

This is the general status description and not an example (the reason there is no example is this warning is kind of internal and only occur for things like memory errors in runtime so it is a bit hard to make a good example)

2024-06-24 09:06 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-149.surge.sh

Updated pages:
- [List of all notification codes](https://neo4j-docs-status-codes-149.surge.sh/status-codes/5/notifications/all-notifications)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-24 11:03 UTC, Lojjs approved these changes

2024-06-24 12:51 UTC, merged