Merge 'gql-notifications' into 'dev'
neo4j/docs-status-codes pull request #171
Opened 2024-08-27 11:30 UTC by NataliaIvakina

2024-08-27 11:31 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-171.surge.sh

Updated pages:
- [Changes to status codes per Neo4j version](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/changelogs)
- [List of all server error codes](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/errors/all-errors)
- [Server errors](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/errors)
- [Introduction](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5)
- [List of all server notification codes](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/notifications/all-notifications)
- [Server notifications](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/notifications)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-27 11:38 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-171.surge.sh

Updated pages:
- [Changes to status codes per Neo4j version](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/changelogs)
- [List of all server error codes](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/errors/all-errors)
- [Server errors](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/errors)
- [Introduction](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5)
- [List of all server notification codes](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/notifications/all-notifications)
- [Server notifications](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/notifications)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-27 15:44 UTC, recrwplay requested changes

2024-08-27 15:44 UTC, recrwplay commented on .github/workflows/docs-pr-checks.yml
> +    - "gql-notifications"
Assuming we are going to delete this branch after merging, we don't need to include it here

2024-08-27 15:44 UTC, recrwplay commented on .github/workflows/docs-teardown.yml
> +      - "gql-notifications"
Same as for `docs-pr-checks.yml`. Assuming we are going to delete this branch after merging, we don't need to include it here

2024-08-28 06:22 UTC, NataliaIvakina commented on .github/workflows/docs-pr-checks.yml
> +    - "gql-notifications"
```suggestion
```

2024-08-28 06:22 UTC, NataliaIvakina commented on .github/workflows/docs-teardown.yml
> +      - "gql-notifications"
```suggestion
```

2024-08-28 06:24 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-171.surge.sh

Updated pages:
- [Changes to status codes per Neo4j version](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/changelogs)
- [List of all server error codes](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/errors/all-errors)
- [Server errors](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/errors)
- [Introduction](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5)
- [List of all server notification codes](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/notifications/all-notifications)
- [Server notifications](https://neo4j-docs-status-codes-171.surge.sh/status-codes/5/notifications)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-28 11:33 UTC, recrwplay approved these changes

2024-08-28 11:33 UTC, merged