Document errors implemented in 2025.01
neo4j/docs-status-codes pull request #243
Opened 2024-12-24 12:22 UTC by renetapopova

2024-12-24 12:24 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-243.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-243.surge.sh/status-codes/2025.01/errors/gql-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-07 11:15 UTC, Lojjs requested changes
Just a bunch of smaller things.

There are also some additional new error codes, you could add too. Either as part of this PR or in a separate one after the others go in, if that is easier. 22G05 I think you have missed since it was in the standard-defined sheet, the rest have been added by @sherfert  and @WilcoNeo during the holidays:

Not in docs
- [x] 22G05
- [x] 42I41
- [ ] 42N62
- [ ] 50N10
- [ ] 50N13
- [ ] 50N14
- [ ] 50N15
- [ ] 51N62
- [ ] 52N22

Commented-out in docs
- [x] 22N65
- [x] 22N70
- [x] 22N73
- [x] 22N74
- [x] 22N75
- [x] 22N76

2025-01-07 11:15 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: system configuration or operation exception - memory pool out of memory. Failed to allocate memory in a memory pool. See `{ $cfgSetting }` in the neo4j configuration.
```suggestion
Status description:: error: system configuration or operation exception - memory pool out of memory. Failed to allocate memory in a memory pool. See `{ $cfgSetting }` in the neo4j.conf file.
```

I think this and the two below were changed based on PR feedback after you made this PR.

2025-01-07 11:15 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: system configuration or operation exception - transaction memory limit reached. The transaction used more memory than was allowed. The maximum allowed size for a transacti
```suggestion
Status description:: error: system configuration or operation exception - transaction memory limit reached. The transaction used more memory than was allowed. The maximum allowed size for a transaction can be configured with `{ $cfgSetting }` in the neo4j.conf file.
```

2025-01-07 11:15 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: system configuration or operation exception - maximum number of transactions reached. Failed to start a new transaction. The limit of concurrent transactions is reached. I
```suggestion
Status description:: error: system configuration or operation exception - maximum number of transactions reached. Failed to start a new transaction. The limit of concurrent transactions is reached. Increase the number of concurrent transactions using `{ $cfgSetting }` in the neo4j.conf file.
```

2025-01-07 11:15 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: procedure exception - invalid procedure argument with API documentation hint. Invalid argument `{ $value }` for `{ $procParam }` on procedure `{ $proc }`. The expected for
```suggestion
Status description:: error: procedure exception - invalid procedure argument with API documentation hint. Invalid argument `{ $field }` for `{ $procParam }` on procedure `{ $proc }`. The expected format of `{ $procParam }` is outlined in the `{ $procParamFmt }` API documentation.
```

This one was different in spreadsheet and implementation, I have updated the spreadsheet.

2025-01-07 11:15 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +
Maybe it does not matter as you are anyway doing a refactoring in one of your other PRs but in this format we should start a new subsection for Function exception here

2025-01-14 15:54 UTC, dogofbrian commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode 'REPEATABLE
Agree with @Lojjs. Also it turns out that, for now at least, we don't think it's safe to allow just path selectors under repeatable elements. So there is only one fix, adding an upper bound to any quantified path pattern. 

Here is my suggested change:

```suggestion
Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode 'REPEATABLE ELEMENTS'. Add an upper bound to the quantified path pattern.
```

2025-01-14 16:24 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - invalid use of `REPORT STATUS`. 'REPORT STATUS' can only be used when specifying 'ON ERROR CONTINUE' or 'ON ERROR BREAK'.
Yes, we need to discuss it and make it consistent in both docs and codebase. It might make sense to leave the backticks for the docs only unless something needs to be explicitly quoted in the codebase.

2025-01-14 16:25 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode 'REPEATABLE
I agree with you. I'll update it here.

2025-01-14 16:27 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +
You're right. I'll add it here as well.

2025-01-14 16:31 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +=== 53N34
```suggestion
== Function exceptions

=== 53N34
```

2025-01-16 07:47 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode 'REPEATABLE
@renetapopova If you change it like this (also remove the path selector part) here in docs, I can fix it in the spreadsheet and codebase. I anyway plan to implement the last error code for planner today so can fix this in the same PR.

2025-01-16 08:25 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode 'REPEATABLE
Updated in the codebase here https://github.com/neo-technology/neo4j/pull/29116

2025-01-22 16:13 UTC, Lojjs reviewed
Had another look, found some minor things as usual

2025-01-22 16:13 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: procedure exception - invalid procedure argument. Invalid argument `{ $value }` for `{ $procParam }` on procedure `{ $proc }`. The expected format of `{ $procParam }` is `
```suggestion
Status description:: error: procedure exception - invalid procedure argument. Invalid argument `{ $field }` for `{ $procParam }` on procedure `{ $proc }`. The expected format of `{ $procParam }` is `{ $procParamFmt }`.
```

This one was inconsistent between spreadsheet and codebase, I have updated the spreadsheet now

2025-01-22 16:13 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode 'REPEATABLE
@NataliaIvakina FYI, this commented is still unhandled (or rather Reneta only fixed my complaint and not Finbar's)

2025-01-24 12:44 UTC, NataliaIvakina commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE
```suggestion
Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE ELEMENTS'. Add an upper bound to the quantified path pattern.
```

2025-01-24 13:50 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE
Doesn't this become wrong because now again REPEATABLE ELEMENTS have different quote before and after. I'm fine with either quoting for now but if they are different I suspect it will screw up docs formatting

2025-01-24 13:59 UTC, NataliaIvakina commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE
```suggestion
Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE ELEMENTS`. Add an upper bound to the quantified path pattern.
```

2025-01-24 14:02 UTC, NataliaIvakina commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: syntax error or access rule violation - unsafe usage of repeatable elements. The quantified path pattern may yield an infinite number of rows under match mode `REPEATABLE
My bad. I fixed backticks

2025-01-27 14:18 UTC, NataliaIvakina commented
@renetapopova hey! I've resolved conflicts here. Could you take a final look? I think we can merge this PR

2025-01-27 14:18 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-243.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-243.surge.sh/status-codes/2025.01/errors/gql-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-27 17:31 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: data exception - index conflicts with existing constraint. An index that belongs to the constraint `{ $constr }` contains a conflicting index.
This sounds odd. I guess we are trying to say
```suggestion
Status description:: error: data exception - index conflicts with existing constraint. Index conflict with an already existing index that belongs to the constraint `{ $constr }`.
```

2025-01-27 18:10 UTC, renetapopova reviewed
I found some discrepancies with the codebase.

2025-01-27 18:10 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: procedure exception - custom procedure execution error cause. Execution of the procedure `{ $proc }` failed due to `{ $msgTitle }`: { $msg }
```suggestion
Status description:: error: procedure exception - custom procedure execution error cause. Execution of the procedure `{ $proc }` failed due to `{ $msgTitle }`: { $msg }.
```

2025-01-27 18:10 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: function exception - function restricted. `{ $fun }` is is restricted and accesses database internals. User-defined function restriction is controlled by the dbms.security
```suggestion
Status description:: error: function exception - function restricted. `{ $fun }` is restricted and accesses database internals. User-defined function restriction is controlled by the `dbms.security.procedures.unrestricted` setting. Only un-restrict user-defined functions you can trust with access to database internals.
```

2025-01-27 18:10 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: function exception - custom function execution error cause. Execution of the function `{ $fun }` failed due to `{ $msgTitle }`: { $msg }
```suggestion
Status description:: error: function exception - custom function execution error cause. Execution of the function `{ $fun }` failed due to `{ $msgTitle }`: { $msg }.
```

2025-01-28 09:16 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors.adoc
> +Status description:: error: data exception - index conflicts with existing constraint. An index that belongs to the constraint `{ $constr }` contains a conflicting index.
As Satia were on vacation, I made a card for this one, so we can fix it later. Because if we fix it in the codebase, that will not be in 2025.01 anyway

2025-01-28 09:37 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-243.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-243.surge.sh/status-codes/2025.01/errors/gql-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-28 09:38 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-243.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-243.surge.sh/status-codes/2025.01/errors/gql-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-28 09:39 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-243.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-243.surge.sh/status-codes/2025.01/errors/gql-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-28 09:42 UTC, merged