Create a page for each GQLSTATUS error and update the structure
neo4j/docs-status-codes pull request #245
Opened 2024-12-27 12:01 UTC by renetapopova

Need to include also the codes from https://github.com/neo4j/docs-status-codes/pull/249/files

2024-12-27 12:02 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-12-27 12:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-13 19:45 UTC, Lojjs requested changes
Great work with this massive PR! Most of my comments are small (like copy-paste errors and such), the two bigger ones we can discuss in an upcoming sync

2025-01-13 19:45 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/25N04.adoc
> +error: invalid transaction state - specified transaction does not exist.
```suggestion
error: invalid transaction state - specified transaction does not exist. Transaction `{ $transactionId }` does not exist.
```

This one is missing the message part.

2025-01-13 19:45 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/42I05.adoc
> +error: syntax error or access rule violation - invalid FIELDTERMINATOR. The FIELDTERMINATOR specified for LOAD CSV can only be one character wide. The FIELDTERMINATOR specified for LOAD CSV can only
The sentence 

The FIELDTERMINATOR specified for LOAD CSV can only be one character wide.

is duplicated by misstake. This was already wrong before the split, but I didn't notice it until now. If we decide to keep the status descriptions in the index file as well, it should be updated in both places.

2025-01-13 19:45 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/42N29.adoc
> +error: syntax error or access rule violation - unbound variables in pattern expression. Pattern expressions are not allowed to introduce new variables: `{ $var }`.
```suggestion
error: syntax error or access rule violation - unbound variables in pattern expression. Pattern expressions are not allowed to introduce new variables: `{ $variable }`.
```

This was already wrong before the split, but I didn't notice it until now. If we decide to keep the status descriptions in the index file as well, it should be updated in both places.

2025-01-13 19:45 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/51N14.adoc
> +error: system configuration or operation exception - duplicate field name.
```suggestion
error: system configuration or operation exception - duplicate field name. The procedure `{ $proc }` has a duplicate `{ $procFieldType }` field, `{ $procField }`.
```

This one is also missing its message part

2025-01-28 10:59 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-28 19:15 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-03 17:06 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-03 17:07 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors/index.adoc
>  Status description:: error: connection exception
I kept them for now. We can always delete them later.

2025-02-03 17:10 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-04 08:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/index.adoc
>  Status description:: error: connection exception
Yes we decided in the error meeting to keep them, but to try to auto-generate this page. Did you make a Trello card for that @renetapopova?

2025-02-04 08:34 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors/index.adoc
>  Status description:: error: connection exception
Yes, I'll open a separate PR with the scripts.

2025-02-04 10:25 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/22N98.adoc
> +error: data exception - wrong first field during deserialization. Unable to deserialize request. Expected first field to be `{ $field }`, but was '{ $value }'.
Ah, I see. All parameters have various quoting, it can be backticks, single quotes, no quotes etc. depending on the type of processor as listed in 'Shared parameter prefixes' in the spreadsheet. **value** is a bit special and has its own processor with no quoting as it can be both a string, boolean or number. In this specific case, quoting was wanted so it was added explicitly added in this way it seems. 

Generally we always have used backticks in docs no matter the real quoting so far, so for consistency I think it would make sense with backticks here as well

2025-02-04 14:48 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/52N35.adoc
> +error: procedure exception - procedure compilation failed. Failed to compile procedure/function defined in `{ $procClass }`: `{ $msg }`
```suggestion
error: procedure exception - procedure compilation failed. Failed to compile procedure defined in `{ $procClass }`: `{ $msg }`
```

I changed this one when created 53N35, but missed to update in https://github.com/neo4j/docs-status-codes/pull/243

2025-02-04 14:49 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/index.adoc
>  Status description:: error: procedure exception - procedure compilation failed. Failed to compile procedure/function defined in `{ $procClass }`: `{ $msg }`
```suggestion
Status description:: error: procedure exception - procedure compilation failed. Failed to compile procedure defined in `{ $procClass }`: `{ $msg }`
```

I changed this one when created 53N35, but missed to update in https://github.com/neo4j/docs-status-codes/pull/243

2025-02-04 15:07 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/42N76.adoc
> +error: syntax error or access rule violation - unfulfillable hints. The hint(s) `{ $hintAndedList }` cannot be fulfilled.
```suggestion
error: syntax error or access rule violation - unfulfillable hints. The hint(s) `{ $hintAndedList }` cannot be fulfilled.
```
```suggestion
error: syntax error or access rule violation - unfulfillable hints. The hint(s) `{ $hintList }` cannot be fulfilled.
```

Something from before which we missed

2025-02-04 15:09 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/index.adoc
>  Status description:: error: syntax error or access rule violation - variable already bound. Node `{ $var }` has already been bound and cannot be modified by the `{ $clause }` clause.
```suggestion
Status description:: error: syntax error or access rule violation - variable already bound. Node `{ $variable }` has already been bound and cannot be modified by the `{ $clause }` clause.
```

Something from before which we missed

2025-02-04 15:46 UTC, renetapopova commented on modules/ROOT/pages/errors/gql-errors/42NA5.adoc
> +info: accessing multiple graphs only supported on composite databases. Accessing multiple graphs in the same query is only supported on composite databases. Connect to a composite database with the d
That's a very good catch!

2025-02-04 16:00 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-04 16:10 UTC, Lojjs reviewed
I was not very clear, meant like this

2025-02-04 16:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/42NA5.adoc
> +error: accessing multiple graphs only supported on composite databases. Accessing multiple graphs in the same query is only supported on composite databases. Connect to a composite database with the
```suggestion
error: syntax error or access rule violation - accessing multiple graphs only supported on composite databases. Accessing multiple graphs in the same query is only supported on composite databases. Connect to a composite database with the desired constituents.
```

2025-02-04 16:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/42NA6.adoc
> +error: invalid alias target. Aliases are not allowed to target composite databases.
```suggestion
error: syntax error or access rule violation - invalid alias target. Aliases are not allowed to target composite databases.
```

2025-02-04 16:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/42NA7.adoc
> +error: referenced database not found. No database is corresponding to `{ $db }`. Verify that the elementId is correct.
```suggestion
error: syntax error or access rule violation - referenced database not found. No database is corresponding to `{ $db }`. Verify that the elementId is correct.
```

2025-02-04 16:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/index.adoc
> +Status description:: error: accessing multiple graphs only supported on composite databases. Accessing multiple graphs in the same query is only supported on composite databases. Connect to a composi
```suggestion
Status description:: error: syntax error or access rule violation - accessing multiple graphs only supported on composite databases. Accessing multiple graphs in the same query is only supported on composite databases. Connect to a composite database with the desired constituents.
```

2025-02-04 16:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/index.adoc
> +Status description:: error: invalid alias target. Aliases are not allowed to target composite databases.
```suggestion
Status description:: error: syntax error or access rule violation - invalid alias target. Aliases are not allowed to target composite databases.
```

2025-02-04 16:10 UTC, Lojjs commented on modules/ROOT/pages/errors/gql-errors/index.adoc
> +Status description:: error: referenced database not found. No database is corresponding to `{ $db }`. Verify that the elementId is correct.
```suggestion
Status description:: error: referenced database not found. No database is corresponding to `{ $db }`. Verify that the elementId is correct.
```
```suggestion
Status description:: error: syntax error or access rule violation - referenced database not found. No database is corresponding to `{ $db }`. Verify that the elementId is correct.
```

2025-02-04 16:14 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-04 16:15 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-245.surge.sh

New pages:
- [08000](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08000)
- [08007](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08007)
- [08N00](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N00)
- [08N01](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N01)
- [08N02](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N02)
- [08N03](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N03)
- [08N04](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N04)
- [08N05](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N05)
- [08N06](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/gql-errors/08N06)

Updated pages:
- [List of Neo4j error codes](https://neo4j-docs-status-codes-245.surge.sh/status-codes/2025.01/errors/all-errors)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-04 16:15 UTC, Lojjs approved these changes
👏 All good now!

2025-02-04 16:15 UTC, merged